twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/public/assets/plugins/bootstrap/': bootstrap
        '%kernel.project_dir%/public/assets/css/': styles
        '%kernel.project_dir%/public/assets/js/': js
        '%kernel.project_dir%/public/assets/images/': images
        '%kernel.project_dir%/public/assets/plugins/': plugins


when@test:
    twig:
        strict_variables: true
